# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6995ed4436ae8c05c934fb5e31661c58775c75544167e96b1ec704570457afbaeb48f3bae8997c55c0294dac7e3f23b15a57c487474255779820223881c2c8fb

test:
  secret_key_base: 5e0747c50335171aade8dd5c5284435cd294368d5f31b44817752c488d61d57502aaafb9828bd171bede14d06f6c5b9344fa2976037ee38c7dd5cc4d8ef7d7db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
